### PR TITLE
Added @JsonCodec #76

### PR DESCRIPTION
**Pull request by reactormonk**
Should I backport to version 1.0 too?

### CODE REVIEW

**Comment by alexarchambault** [comment]
Really cool!

About the additions to the README, the one at the root of the project is actually generated by [tut](https://github.com/tpolecat/tut), from the one under `doc/`. You should change the latter first, possibly adding some code sections with the right tut syntax so that they are tested by tut, then run `sbt tut`.

See the `tut:invisible` sections in the current [`doc/README.md`](https://raw.githubusercontent.com/alexarchambault/argonaut-shapeless/master/doc/README.md), that ensure the corresponding code runs fine. There are also some `tut:silent` ones for a few asserts, that are run but not shown in the final README.

About the port to 1.0, do it if you think you'll use it. Else, that's not absolutely necessary IMO (shapeless 2.3 phased out shapeless 2.2, that argonaut-shapeless 1.0 depends on, some months ago now).

**Comment by reactormonk** [comment]
Ah, 1.1.0 and 1.1.1 for the two scalaz versions - could you drag it over?

How would I bring `JsonCodec` into `ArgonautShapeless` scope? Should I do that at all?

**Comment by alexarchambault** [comment]
What do you mean about 1.1.0 and 1.1.1? Yeah, the second depends on scalaz 7.2 via argonaut 6.1a. I now think that was a mistake to switch to it, it should have been either its own branch, or at least be published with module name `argonaut-shapeless_6.1a` instead of `argonaut-shapeless_6.1` (which can still be fixed btw). Is it a problem for you? I think I'll fix that in the coming days.

About `JsonCodec`, it can be brought via `ArgonautShapeless`, yes. Either a type alias if it's fine, or by moving the `JsonCodec` class altogether there.

**Comment by reactormonk** [comment]
I'd prefer one version on scalaz 7.1, but I'll check if I could upgrade to 7.2

I tried via type alias, didn't work for me (didn't find the value), and via `val` it couldn't expand the macro.

**Comment by alexarchambault** [comment]
@reactormonk Are you ok for merging? I'm fine with the current state of it, a workaround to move it to `ArgonautShapeless ` could be found later.

**Comment by reactormonk** [comment]
Merge it.

**Pull request merged**
