### PR TITLE
Add contributors section in README

### PR DESCRIPTION
**Pull request by alexarchambault**
About to add a contributors section in the README.

### CODE REVIEW

**Comment by alexarchambault** [comment]
@bmjames @notxcain @fthomas @ijuma pinging you here, as contributors, just so you know, and to ensure you're fine with it.

**Comment by fthomas** [comment]
:+1:

**Comment by alexarchambault** [comment]
@bmjames @notxcain @ijuma considering it's a yes from you too, feel free to ping me if you think otherwise!

**Comment by ijuma** [comment]
Thanks @alexarchambault.

**Pull request merged**
