### PR TITLE
Support explicit codec materialization.

### PR DESCRIPTION
**Pull request by tixxit**
Rather than having derivation to be implicit, this allows the user to choose to continue importing the Shapeless._ object for implicits, or use, eg, `AutoEncodeJson.derive[Foo]` to be more explicit.

For example, I would likely do something like:

``` scala
case class Foo(x: Int)

...

implicit val FooCodecJson: CodecJson[Foo] = AutoCodecJson.derive[Foo]
```

I had to remove the `Lazy` wrappers, otherwise the implicit resolution failed. I'm not sure why this is. `-Xlog-implicits` said the error was that `mkLazy` was returning a `Lazy[Nothing]` rather than a `Lazy[EncodeJson[Int]]` where required. So the type was lost somehow and it was failing.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks, I think it would indeed be a good idea if we could generate auto codec only for a few classes without importing the whole `Shapeless` namespace. But only in addition to the way they are currently used.

I updated the tests with more complex examples, that `Lazy` was precisely tailored to handle. And as I expected, removing it (tested that with your code) breaks some of them.

I'll look more closely at your code, and/or try to find a solution to have both ways together.

**Comment by alexarchambault** [comment]
Here are the errors I get when using your code with the new tests:

```scala
[info] Compiling 4 Scala sources to /home/alexandre/projects/argonaut-shapeless/target/scala-2.10/classes...
[info] Compiling 1 Scala source to /home/alexandre/projects/argonaut-shapeless/target/scala-2.10/test-classes...
[error] /home/alexandre/projects/argonaut-shapeless/src/test/scala/argonaut/shapeless/Tests.scala:67: diverging implicit expansion for type argonaut.EncodeJson[argonaut.shapeless.Composed]
[error] starting with method autoCodecJson in trait AutoCodecJsons
[error]     sameAfterBeforeSerialization[Composed]
[error]                                 ^
[error] /home/alexandre/projects/argonaut-shapeless/src/test/scala/argonaut/shapeless/Tests.scala:71: diverging implicit expansion for type argonaut.EncodeJson[argonaut.shapeless.TwiceComposed]
[error] starting with method autoCodecJson in trait AutoCodecJsons
[error]     sameAfterBeforeSerialization[TwiceComposed]
[error]                                 ^
[error] /home/alexandre/projects/argonaut-shapeless/src/test/scala/argonaut/shapeless/Tests.scala:75: diverging implicit expansion for type argonaut.EncodeJson[argonaut.shapeless.ComposedOptList]
[error] starting with method autoCodecJson in trait AutoCodecJsons
[error]     sameAfterBeforeSerialization[ComposedOptList]
[error]                                 ^
[error] /home/alexandre/projects/argonaut-shapeless/src/test/scala/argonaut/shapeless/Tests.scala:83: diverging implicit expansion for type argonaut.EncodeJson[argonaut.shapeless.Base]
[error] starting with method autoCodecJson in trait AutoCodecJsons
[error]     sameAfterBeforeSerialization[Base]
[error]                                 ^
[error] four errors found
[error] (test:compile) Compilation failed
[error] Total time: 7 s, completed 6 janv. 2015 22:59:53
```

**Comment by alexarchambault** [comment]
By the way, are you aware of the macro-based derivation recently in argonaut ?

**Comment by tixxit** [comment]
OK, great! Yeah, I assumed the `Lazy` was required, but wanted to get this up here so more eyeballs could see it, since I was stumped as the failure with `Lazy` (*cough* @milessabin *cough*).

**Comment by tixxit** [comment]
@alexarchambault Somewhat aware. Last time I saw, Sean seemed like he wanted to drop Shapeless and move to macros, so haven't seen the implementation yet.

**Comment by alexarchambault** [comment]
Tested it (in - minor - cases where the automatic one with shapeless didn't work, but shhh..), it seems to work.

**Pull request closed without merging**
